version: '3.3'

services:
  drupal:
    image: drupal:latest
    ports:
      - 81:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: mansi
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  mysql_storage_new:
